import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { readFileSync, readdirSync, existsSync, writeFileSync } from "node:fs";
import { join, extname, relative, basename } from "node:path";
import type { Config } from "../config.js";
import { validateProjectPath } from "../utils/safe-path.js";

function walk(dir: string, cb: (full: string, rel: string)=>void, base=dir){
  let e; try{ e=readdirSync(dir,{withFileTypes:true}); }catch{return;}
  for(const ent of e){
    if(ent.name.startsWith(".")) continue;
    const full=join(dir,ent.name);
    if(ent.isDirectory()) walk(full,cb,base);
    else cb(full, relative(base,full).replace(/\\/g,"/"));
  }
}

export function registerFactionScenario(server: McpServer, config: Config): void {
  server.registerTool("faction_create", {
    description: "Scaffold a faction config .conf (side, loadouts, units). Offline.",
    inputSchema: { name: z.string().describe("Faction name, e.g. MyFaction"), projectPath: z.string().optional().describe("Mod project directory"), side: z.enum(["BLUFOR","OPFOR","INDFOR","CIV"]).default("BLUFOR").describe("Side") }
  }, async ({ name, projectPath, side }) => {
    const base = projectPath || config.projectPath;
    if(!base || !existsSync(base)) return { content:[{type:"text" as const, text:"No project path."}], isError:true };
    const outPath = join(base, `Configs/Factions/${name}.conf`);
    const content = `// ${name} faction — generated by Forge-X\nFaction ${name} {\n side "${side}"\n // Add loadouts: see SCR_FactionConfig\n}\n`;
    try {
      const dir = join(base, "Configs/Factions");
      if(!existsSync(dir)) { const { mkdirSync } = await import("node:fs"); mkdirSync(dir,{recursive:true}); }
      writeFileSync(outPath, content, "utf-8");
      return { content:[{type:"text" as const, text: `**Faction ${name} created:** \`${relative(base,outPath).replace(/\\/g,"/")}\``}] };
    } catch(e){ return { content:[{type:"text" as const, text:String(e)}], isError:true }; }
  });

  server.registerTool("faction_list_units", {
    description: "Group a project's units by faction (scans .conf faction refs). Offline.",
    inputSchema: { projectPath: z.string().optional().describe("Mod project directory") }
  }, async ({ projectPath }) => {
    const base = projectPath || config.projectPath;
    if(!base || !existsSync(base)) return { content:[{type:"text" as const, text:"No project path."}], isError:true };
    const byFaction = new Map<string,string[]>();
    walk(base,(full,rel)=>{
      if(extname(full).toLowerCase()!==".conf") return;
      try{
        const c=readFileSync(full,"utf-8");
        const fac = c.match(/faction\s+"?(\w+)"?/i);
        if(fac) {
          const list=byFaction.get(fac[1])||[];
          list.push(rel);
          byFaction.set(fac[1],list);
        }
      }catch{}
    });
    if(byFaction.size===0) return { content:[{type:"text" as const, text:"No faction configs found."}] };
    const lines=["**Units by faction:**"];
    for(const [f, files] of byFaction) lines.push(`- **${f}:** ${files.slice(0,5).join(", ")}${files.length>5?` +${files.length-5} more`:""}`);
    return { content:[{type:"text" as const, text: lines.join("\n")}] };
  });

  server.registerTool("scenario_inspect", {
    description: "Inspect a scenario .conf (mission header, factions, layers). Offline.",
    inputSchema: { path: z.string().describe("Scenario .conf path relative to project, e.g. Missions/My.conf"), projectPath: z.string().optional().describe("Mod project directory") }
  }, async ({ path: inputPath, projectPath }) => {
    const base = projectPath || config.projectPath;
    if(!base) return { content:[{type:"text" as const, text:"No project path."}], isError:true };
    let full; try{ full=validateProjectPath(base,inputPath); }catch(e){ return { content:[{type:"text" as const, text:String(e)}], isError:true }; }
    if(!existsSync(full)) return { content:[{type:"text" as const, text:`Not found: ${inputPath}`}], isError:true };
    const c=readFileSync(full,"utf-8");
    const lines=[`## ${inputPath}`, `- **Size:** ${c.split("\n").length} lines`, `- **Factions:** ${[...c.matchAll(/faction\s+"?(\w+)"?/gi)].map(m=>m[1]).join(", ")||"none"}`];
    return { content:[{type:"text" as const, text: lines.join("\n")}] };
  });

  server.registerTool("scenario_diff", {
    description: "Semantic diff of two scenario .conf files. Offline.",
    inputSchema: { a: z.string().describe("First scenario path"), b: z.string().describe("Second scenario path"), projectPath: z.string().optional().describe("Mod project directory") }
  }, async ({ a, b, projectPath }) => {
    const base = projectPath || config.projectPath;
    if(!base) return { content:[{type:"text" as const, text:"No project path."}], isError:true };
    let fa, fb; try{ fa=validateProjectPath(base,a); fb=validateProjectPath(base,b); }catch(e){ return { content:[{type:"text" as const, text:String(e)}], isError:true }; }
    if(!existsSync(fa)||!existsSync(fb)) return { content:[{type:"text" as const, text:"One file not found."}], isError:true };
    const ca=readFileSync(fa,"utf-8").split("\n"), cb=readFileSync(fb,"utf-8").split("\n");
    const onlyA=ca.filter(l=>!cb.includes(l)).slice(0,20), onlyB=cb.filter(l=>!ca.includes(l)).slice(0,20);
    return { content:[{type:"text" as const, text: `**Diff ${a} vs ${b}:**\n- Only in A (${onlyA.length}):\n${onlyA.map(s=>`  - ${s.trim().slice(0,80)}`).join("\n")}\n- Only in B (${onlyB.length}):\n${onlyB.map(s=>`  - ${s.trim().slice(0,80)}`).join("\n")}`}] };
  });

  server.registerTool("scenario_clone_area", {
    description: "Clone a rectangular area of a layer with regenerated GUIDs (offline file copy + GUID regen).",
    inputSchema: { layerPath: z.string().describe("Layer file path, e.g. worlds/My/Missions/My.conf"), projectPath: z.string().optional().describe("Mod project directory") }
  }, async ({ layerPath, projectPath }) => {
    const base = projectPath || config.projectPath;
    if(!base) return { content:[{type:"text" as const, text:"No project path."}], isError:true };
    let full; try{ full=validateProjectPath(base,layerPath); }catch(e){ return { content:[{type:"text" as const, text:String(e)}], isError:true }; }
    if(!existsSync(full)) return { content:[{type:"text" as const, text:`Not found: ${layerPath}`}], isError:true };
    const content=readFileSync(full,"utf-8");
    // Simple GUID regen: replace 16-hex GUIDs with new random
    const newContent=content.replace(/\b([0-9A-Fa-f]{16})\b/g,()=>Array.from({length:16},()=>Math.floor(Math.random()*16).toString(16)).join("").toUpperCase());
    const out=full.replace(/\.conf$/,"_clone.conf");
    writeFileSync(out,newContent,"utf-8");
    return { content:[{type:"text" as const, text: `**Cloned:** \`${relative(base,out).replace(/\\/g,"/")}\` (GUIDs regenerated)`}] };
  });
}
